### ISSUE TITLE
Stopping Express server

### ISSUE THREAD

**Issue by theraw** [ovh-ux/ovh-manager-cloud#360]
### Error

```bash
Running "express:dev" (express) task
Starting background Express server
(node:3573) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.
Stopping Express server
```

Right after installation trying to use `make dev` i got that error. 

node version `v8.0.0`
npm version `v5.0.0`
grunt version `grunt-cli v1.2.0, grunt v1.0.1`
bower version `1.8.2`

However a fast solution which i found was to turn off debug mode https://github.com/ovh-ux/ovh-manager-cloud/blob/master/Gruntfile.js#L51

Good work btw. i was thinking this is a custom panel i didn't expect to see original ovh panel..

This is just a report so you can close after you read this.

**Comment by Netnix** [comment]
Thank you for the feedback !

Indeed, this warning only appears for version v8.0.0 of node and above.

I've simply removed the debug mode in order to be consistent with our other managers (web (https://github.com/ovh-ux/ovh-manager-web/blob/master/Gruntfile.js#L83) and telecom (https://github.com/ovh-ux/ovh-manager-telecom/blob/master/Gruntfile.js#L63)).
